remove npm

diff --git a/.github/workflows/default.yml b/.github/workflows/default.yml
--- a/.github/workflows/default.yml
+++ b/.github/workflows/default.yml
@@ -1,9 +1,37 @@
 name: default
 on: [push]
 jobs:
-  without-node:
+  test1:
     runs-on: ${{ matrix.virtual-environment }}
     strategy:
+      fail-fast: false
+      matrix:
+        virtual-environment: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04]
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2
+      - # Expecting: build ok
+        # Actual behavior: build ok
+        name: Build container(s) in docker-compose.works.yml
+        run: docker-compose -f docker-compose.works.yml build
+      - # Expecting: 'invalid reference format: repository name must be lowercase'
+        # Actual behavior: 'Couldn't connect to Docker daemon at http+docker://localhost - is it running?'
+        name: Build container(s) in docker-compose.fails.yml
+        #run: docker-compose -f docker-compose.fails.yml build
+        run: |
+          output=$(docker-compose -f docker-compose.fails.yml build 2>&1 || true)
+          echo "${output}"
+          if ! grep -q 'invalid reference format: repository name must be lowercase' <<< "${output}"; then
+            exit 1
+          fi
+      - # Expecting: build ok
+        # Actual behavior: build ok
+        name: Build container(s) in docker-compose.works.yml
+        run: docker-compose -f docker-compose.works.yml build
+  test2:
+    runs-on: ${{ matrix.virtual-environment }}
+    strategy:
+      fail-fast: false
       matrix:
         virtual-environment: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04]
     steps:
@@ -18,6 +46,7 @@ jobs:
         name: Build container(s) in docker-compose.fails.yml
         #run: docker-compose -f docker-compose.fails.yml build
         run: |
+          rm -rf .git
           output=$(docker-compose -f docker-compose.fails.yml build 2>&1 || true)
           echo "${output}"
           if ! grep -q 'invalid reference format: repository name must be lowercase' <<< "${output}"; then
@@ -27,35 +56,26 @@ jobs:
         # Actual behavior: build ok
         name: Build container(s) in docker-compose.works.yml
         run: docker-compose -f docker-compose.works.yml build
-  with-node:
+  test3:
     runs-on: ${{ matrix.virtual-environment }}
     strategy:
       fail-fast: false
       matrix:
-        virtual-environment: [ubuntu-20.04, ubuntu-18.04, ubuntu-16.04]
-        node-version: [10, 12, 14]
-        node-package: [lodash, tslib, request, debug, prop-types]
+        virtual-environment: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04]
+        file: ["ajv", "dashdash", "fast-json-stable-stringify", "form-data", "isstream", "json-schema", "jsprim", "mime-types", "performance-now", "qs", "safe-buffer", "sshpk", "tough-cookie", "tweetnacl", "uuid", "verror"]
     steps:
       - name: Checkout
         uses: actions/checkout@v2
-      - name: Install node
-        uses: actions/setup-node@v1
-        with:
-          node-version: ${{ matrix.node-version }}
-      - name: Install npm package(s)
-        run: npm install --no-save --ignore-scripts ${{ matrix.node-package }}
       - # Expecting: build ok
         # Actual behavior: build ok
         name: Build container(s) in docker-compose.works.yml
         run: docker-compose -f docker-compose.works.yml build
       - # Expecting: 'invalid reference format: repository name must be lowercase'
-        # Actual behavior:
-        #  'Couldn't connect to Docker daemon at http+docker://localhost - is it running?'
-        #  OR
-        #  'invalid reference format: repository name must be lowercase'
+        # Actual behavior: 'invalid reference format: repository name must be lowercase'
         name: Build container(s) in docker-compose.fails.yml
         #run: docker-compose -f docker-compose.fails.yml build
         run: |
+          find node_modules -mindepth 1 -maxdepth 1 -type d ! -name ${{ matrix.file }} -exec rm -rf {} \;
           output=$(docker-compose -f docker-compose.fails.yml build 2>&1 || true)
           echo "${output}"
           if ! grep -q 'invalid reference format: repository name must be lowercase' <<< "${output}"; then
@@ -65,37 +85,27 @@ jobs:
         # Actual behavior: build ok
         name: Build container(s) in docker-compose.works.yml
         run: docker-compose -f docker-compose.works.yml build
-  with-node-workaround:
+  test4:
     runs-on: ${{ matrix.virtual-environment }}
     strategy:
       fail-fast: false
       matrix:
-        virtual-environment: [ubuntu-20.04, ubuntu-18.04, ubuntu-16.04]
-        node-version: [10, 12, 14]
-        node-package: [lodash, tslib, request, debug, prop-types]
+        virtual-environment: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04]
+        file: ["ajv", "dashdash", "fast-json-stable-stringify", "form-data", "isstream", "json-schema", "jsprim", "mime-types", "performance-now", "qs", "safe-buffer", "sshpk", "tough-cookie", "tweetnacl", "uuid", "verror"]
     steps:
       - name: Checkout
         uses: actions/checkout@v2
-      - name: Install node
-        uses: actions/setup-node@v1
-        with:
-          node-version: ${{ matrix.node-version }}
-      - name: Install npm package(s)
-        run: npm install --no-save --ignore-scripts ${{ matrix.node-package }}
-      - name: (workaround) Delete all *.js files
-        run: find node_modules -type f -name *.js -delete
       - # Expecting: build ok
         # Actual behavior: build ok
         name: Build container(s) in docker-compose.works.yml
         run: docker-compose -f docker-compose.works.yml build
       - # Expecting: 'invalid reference format: repository name must be lowercase'
-        # Actual behavior:
-        #  'Couldn't connect to Docker daemon at http+docker://localhost - is it running?'
-        #  OR
-        #  'invalid reference format: repository name must be lowercase'
+        # Actual behavior: 'invalid reference format: repository name must be lowercase'
         name: Build container(s) in docker-compose.fails.yml
         #run: docker-compose -f docker-compose.fails.yml build
         run: |
+          rm -rf .git
+          find node_modules -mindepth 1 -maxdepth 1 -type d ! -name ${{ matrix.file }} -exec rm -rf {} \;
           output=$(docker-compose -f docker-compose.fails.yml build 2>&1 || true)
           echo "${output}"
           if ! grep -q 'invalid reference format: repository name must be lowercase' <<< "${output}"; then
